/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.bean.Movimentacao;
import model.bean.Valor;
import model.dao.MovimentacaoDAO;
import model.dao.ValorDAO;


/**
 *
 * @author dougl
 */
public class Tela_principal extends javax.swing.JFrame {

    /**
     * Creates new form Tela_principal
     */
    public Tela_principal() {
        initComponents();
        initComplementos();
        setTitle("Tela principal");
        DefaultTableModel tabela_principal = (DefaultTableModel) tbl_veiculos.getModel();
        tbl_veiculos.setRowSorter(new TableRowSorter(tabela_principal));
        
        listaJTable();
        
        
        
        
        
    }
    
    public void initComplementos(){
    
        this.setLocationRelativeTo(null);
        
    }
    
    private static String converteData(String data){
       String dataFinal = "";       
       String[] outraData = data.split("/");
       String[] outraData2 = data.split("-");       
       if(!outraData[0].equals(data)){
           dataFinal = outraData[2]+"-"+outraData[1]+"-"+outraData[0];
           return comparaData(dataFinal, data, "[0-9]{4}-([0-1]{1})([0-9]{1})-([0-3]{1})([0-9]{1})");
       }else{           
           dataFinal= outraData2[2]+'/'+outraData2[1]+'/'+outraData2[0];
           return comparaData(dataFinal, data, "([0-3]{1})([0-9]{1})/([0-1]{1})([0-9]{1})/[0-9]{4}");
           
       }       
    }
    private static String comparaData(String dataFinal, String data, String eregex){
        Pattern padrao;
        Matcher m;
        padrao = Pattern.compile(eregex);
           m = padrao.matcher(dataFinal);
           if(!m.find()){
               JOptionPane.showMessageDialog(null, "Data Incorreta amigo");
               return data;
           }
        return dataFinal;
    }
    
    public void listaJTable(){
    
       DefaultTableModel tabela_principal = (DefaultTableModel) tbl_veiculos.getModel();
       tabela_principal.setNumRows(0); 
       MovimentacaoDAO mov = new MovimentacaoDAO();
       DateFormat df = new SimpleDateFormat("dd-MM-yyyy");
       
       
       for(Movimentacao m: mov.lista_de_veiculos()){
       
           
           tabela_principal.addRow(new Object[]{
           
               m.getId(),
               m.getPlaca(),
               m.getModelo(),
               df.format(m.getData_entrada())
           
           
           });
           
       
       }
    
    
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_veiculos = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setText("Veículos estacionados");

        tbl_veiculos.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbl_veiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Placa", "Modelo", "Data de entrada"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_veiculos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tbl_veiculosKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbl_veiculosKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tbl_veiculosKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_veiculos);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Inserir um novo veículo ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton2.setText("Editar veículo ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("Remover veículo do estacionamento");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "           Selecione uma das opções", "               Veículos estacionados", "                     Tela de saída" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        Tela_de_formulario tela = new Tela_de_formulario();
        tela.setVisible(true); 
        
        this.dispose();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tbl_veiculosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_veiculosKeyReleased
        
        
        
    }//GEN-LAST:event_tbl_veiculosKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        
        if(tbl_veiculos.getSelectedRow() != -1){
        
             Movimentacao m = new Movimentacao();
             m.setPlaca(tbl_veiculos.getValueAt(tbl_veiculos.getSelectedRow(), 1).toString());
             m.setModelo(tbl_veiculos.getValueAt(tbl_veiculos.getSelectedRow(), 2).toString());
             m.setId((int) tbl_veiculos.getValueAt(tbl_veiculos.getSelectedRow(), 0)); 
             
             Tela_de_edicao editar = new Tela_de_edicao();
             
             editar.exportar(m); 
             
             editar.setVisible(true);
             
             this.dispose();
             
        
        }
        
        else{
        
        
            JOptionPane.showMessageDialog(null, "Selecione um veículo para atualizar");
        
        
        }
        
        
        
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tbl_veiculosKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_veiculosKeyPressed

    }//GEN-LAST:event_tbl_veiculosKeyPressed

    private void tbl_veiculosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbl_veiculosKeyTyped

    }//GEN-LAST:event_tbl_veiculosKeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        
        if(tbl_veiculos.getSelectedRow() != -1){
          
        Movimentacao mo = new Movimentacao();
        MovimentacaoDAO dao = new MovimentacaoDAO();
       
        mo.setId((int) tbl_veiculos.getValueAt(tbl_veiculos.getSelectedRow(), 0)); 
        
        dao.updatesaida(mo);
        
        Movimentacao mo2 = new Movimentacao();
        MovimentacaoDAO dao2 = new MovimentacaoDAO();
        ValorDAO valo = new ValorDAO();
        
        mo2.setId((int) tbl_veiculos.getValueAt(tbl_veiculos.getSelectedRow(), 0));
        
        for(Movimentacao m1: dao2.lista_de_veiculos_de_saida(mo2)){ 
       
           for(Valor va: valo.lista_dados_tbl_valor()){  
              
               
           long diff = m1.getData_saida() - m1.getData_entrada();

           long diffSeconds = diff / 1000 % 60;
           long diffMinutes = diff / (60 * 1000) % 60;
           long diffHours = diff / (60 * 60 * 1000) % 24;
           long diffDays = diff / (24 * 60 * 60 * 1000);
           
           if(diffHours == 0){
           
               mo2.setTempo("1 hora");
               mo2.setValor_pago(va.getValor_primeira_hora()); 
               mo2.setId((int) tbl_veiculos.getValueAt(tbl_veiculos.getSelectedRow(), 0)); 
           
               dao2.updatesaida2(mo2); 
           
           }
           
           else{
               
           
               if(diffDays != 0){
                   
                   
               double per =  ((diffDays * 24) + diffHours); 
               
               double valor = va.getValor_primeira_hora();
               
               for (int i = 0; i < (per - 1); i++) { 
                   
               valor += va.getValor_demais_horas();
                       
               }
               
               mo2.setTempo(diffDays + " dias " + diffHours + " horas " + diffMinutes + " minutos " + diffSeconds + " segundos");
               mo2.setValor_pago(valor); 
               mo2.setId((int) tbl_veiculos.getValueAt(tbl_veiculos.getSelectedRow(), 0)); 
           
               dao2.updatesaida2(mo2);
               
               
               }
               
               else{
               
               double valor = va.getValor_primeira_hora();;
               
               for (int i = 0; i < (diffHours - 1); i++) { 
                   
               valor += va.getValor_demais_horas();
                       
               }
               
               mo2.setTempo(diffDays + " dias " + diffHours + " horas " + diffMinutes + " minutos " + diffSeconds + " segundos");
               mo2.setValor_pago(valor); 
               mo2.setId((int) tbl_veiculos.getValueAt(tbl_veiculos.getSelectedRow(), 0)); 
           
               dao2.updatesaida2(mo2); 
               
              }
               
               
           
           }
           
        }
                    
       } 
            
       listaJTable();
             
        
        
        }
        
        else{
        
        
            JOptionPane.showMessageDialog(null, "Selecione um veículo para remover do estacionamento");
        
        
        }
        
        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
       
        String itemselecionado = jComboBox1.getSelectedItem().toString();
        
        System.out.println("teste: " + itemselecionado);
        
        if(itemselecionado.equals("               Veículos estacionados")){
        
         this.dispose(); 
        
         Tela_de_veiculo_estacionados tela = new Tela_de_veiculo_estacionados();
         
         tela.setVisible(true);
            
        
        }
        
        if(itemselecionado.equals("                     Tela de saída")){
        
           this.dispose(); 
            
           Tela_de_saida tela = new Tela_de_saida();
           
           tela.setVisible(true);
        
        }
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_veiculos;
    // End of variables declaration//GEN-END:variables
}
